### ISSUE TITLE
Translation for the journal of the German TeX user group

### ISSUE THREAD

**Issue by samcarter** [jolars/jolars.co#28]
I translated your fantastic blog post about the Moloch theme into German. Are you OK with me submitting the translation to "Die TEXnische Komödie", the journal of the German TeX user group?

I made a couple of small changes compared to your blog:
- remove the paragraph about the talk at TUG'24 as the event will probably be in the past when published
- added a footnote which roughly translates to
> Note from the translator: Users of the beamer class can now choose the format of the frametitle themselves, e.g. using `\setbeamertemplate{frametitle}{\MakeUppercase{\insertframetitle}}`. Ironically, it were exactly the internal beamer changes to allow this, which broke the patches of the Metropolis theme.
  
(feel free to incorporate this code into your blog post in case you deem it helpful for your users)

- replaced links with footnotes/\ref (better for print)

The layout is not yet optimised, image placement and page breaks are still rough, but I wanted to wait with these in case the editor would like to make changes.

Draft: [Moloch.pdf](https://github.com/user-attachments/files/15914880/Moloch.pdf)

**Comment by jolars** [comment]
Thanks a lot for this! Absolutely, go ahead.

> (feel free to incorporate this code into your blog post in case you deem it helpful for your users)

Thanks! Absolutely, I'll add this to the post.

**Comment by samcarter** [comment]
Thanks! 

Another question: have you thought about submitting your blog to the TUGboat (https://tug.org/TUGboat/), the journal of the international TeX User Group? I'm just asking because if you happen to plan to submit it, I won't write a proceeding for Moloch talk at TUG'24.

**Comment by jolars** [comment]
I am still considering it, but if so I want to add one or two features first to make it more newsworthy and not just a less feature-rich metropolis :)

**Comment by samcarter** [comment]
Ok, then I'm cautiously optimistic that there will be an article about Moloch at some point and I won't write a proceeding.

(a less feature-rich theme is still better than a broken theme :) )

**Comment by kberry** [comment]
As one of the TUGboat editors: we'd welcome your article, jolars! The blog post looks great. FYI, the deadline for the fall issue of TUGboat is October 4. For a template, etc., please see https://tug.org/TUGboat/location.html. Thanks for considering it.

**Comment by jolars** [comment]
> As one of the TUGboat editors: we'd welcome your article, jolars! The blog post looks great. FYI, the deadline for the fall issue of TUGboat is October 4. For a template, etc., please see https://tug.org/TUGboat/location.html. Thanks for considering it.

Thanks! :)
